from setuptools import setup, find_packages

try:
    _long_description = open("README.md").read()
except FileNotFoundError:
    _long_description = ""

setup(
    name="cog3dmap",
    version="0.1.0",
    packages=find_packages("src"),
    package_dir={"": "src"},
    install_requires=[
        "transformers==5.3.0",
        "deepspeed==0.16.4",
        "flash_attn==2.7.4.post1",
        "triton==3.1.0",
        "accelerate==1.4.0",
        "torchcodec==0.2",
        "black==24.1.0",
        "isort==5.13.2",
        "datasets==3.6.0",
        "evaluate>=0.4.0",
        "httpx==0.25.0",
        "jsonlines",
        "numexpr",
        "numpy==1.26.4",
        "peft>=0.2.0",
        "pybind11>=2.6.2",
        "pytablewriter",
        "sacrebleu>=1.5.0",
        "scikit-learn>=0.24.1",
        "sqlitedict==2.1.0",
        "timm",
        "einops",
        "ftfy",
        "openai",
        "opencv-python-headless",
        "av",
        "hf_transfer",
        "nltk",
        "sentencepiece==0.1.99",
        "yt-dlp",
        "pycocoevalcap",
        "tqdm-multiprocess",
        "transformers-stream-generator",
        "zstandard",
        "pillow",
        "pyyaml",
        "sympy",
        "mpmath",
        "Jinja2",
        "openpyxl",
        "loguru",
        "hf_transfer",
        "tenacity==8.3.0",
        "wandb>=0.16.0",
        "tiktoken",
        "pre-commit",
        "pydantic",
        "packaging",
        "decord",
        "zss",
        "protobuf==3.20",
        "qwen_vl_utils",
        "open3d===0.19.0",
        "spicy==0.16.0",
        "terminaltables",
        "viser",
        "natsort",
        # "causal_conv1d",
        # "flash-linear-attention",
    ],
    author="Chanyoung Gwak*, Yoonwoo Jeong*, Byungwoo Jeon, Hyunseok Lee, Jinwoo Shin, Minsu Cho",
    author_email="gwakcy@postech.ac.kr",
    description="Official PyTorch implementation for \"Cog3DMap: Multi-View Vision-Language Reasoning with 3D Cognitive Maps\"",
    long_description=_long_description,
    long_description_content_type="text/markdown",
    classifiers=[
        "Programming Language :: Python :: 3",
        "Operating System :: OS Independent",
    ],
    python_requires="==3.10.*",
)
